services:
  app:
    container_name: cpml-next
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - JWT_SECRET=${JWT_SECRET}
      - IMAGEKIT_PRIVATE_KEY=${IMAGEKIT_PRIVATE_KEY}
      - IMAGEKIT_PUBLIC_KEY=${IMAGEKIT_PUBLIC_KEY}
      - NEXT_PUBLIC_API=${NEXT_PUBLIC_API}
