import { Toaster } from '@/components/ui/sonner'
import { UserProvider } from '@/lib/auth'
import retrieveUserFromSession from '@/utils/getUser'
import type { Metadata } from 'next'
import { League_Script, Montserrat, Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({
  weight: ['200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-poppins'
})

const leagueScript = League_Script({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-league-script'
})

const montserrat = Montserrat({
  weight: ['200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-montserrat'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const skipApiCall = process.env.NEXT_SKIP_API_CALLS

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const userPromise = retrieveUserFromSession()

  if (skipApiCall) {
    return (
      <html lang='en'>
        <body
          className={`${poppins.className} ${leagueScript.variable} ${montserrat.variable}`}
          suppressHydrationWarning
        >
          <UserProvider userPromise={userPromise}>
            <Toaster richColors closeButton />
            <>{children}</>
          </UserProvider>
        </body>
      </html>
    )
  }

  return (
    <html lang='en'>
      <body
        className={`${poppins.className} ${leagueScript.variable} ${montserrat.variable}`}
        suppressHydrationWarning
      >
        <UserProvider userPromise={userPromise}>
          <Toaster richColors closeButton />
          <>{children}</>
        </UserProvider>
      </body>
    </html>
  )
}
