import { Toaster } from '@/components/ui/sonner'
import { UserProvider } from '@/lib/auth'
import retrieveUserFromSession from '@/utils/getUser'
import type { Metadata } from 'next'
import { Raleway, Roboto } from 'next/font/google'
import './globals.css'

const roboto = Roboto({
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-roboto'
})

const raleway = Raleway({
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin', 'cyrillic'],
  variable: '--font-raleway'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const skipApiCall = process.env.NEXT_SKIP_API_CALLS

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const userPromise = retrieveUserFromSession()

  if (skipApiCall) {
    return (
      <html lang='en'>
        <body
          className={`${roboto.variable} ${raleway.variable}`}
          suppressHydrationWarning
        >
          <UserProvider userPromise={userPromise}>
            <Toaster richColors closeButton />
            <>{children}</>
          </UserProvider>
        </body>
      </html>
    )
  }

  return (
    <html lang='en'>
      <body
        className={`${roboto.variable} ${raleway.variable}`}
        suppressHydrationWarning
      >
        <UserProvider userPromise={userPromise}>
          <Toaster richColors closeButton />
          <>{children}</>
        </UserProvider>
      </body>
    </html>
  )
}
